#!/bin/bash

ipAddress=$(wget -qO- ipv4.icanhazip.com)
if [ "$(cat /sys/module/ipv6/parameters/disable)" -ge 1 ]; then
	ipv6_status="ON"
else
	ipv6_status="OFF"
fi
timezone="$(timedatectl | grep -i 'Time zone' | awk '{print $3}')"
ufwstatus="$(ufw status | grep Status | awk '{print $2}')"
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(netstat -nlpt | grep -i squid | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
badvpnport="$(netstat -nlpt | grep -i badvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
wireguardport="$(wg | grep -i port | awk '{print $3}')"
nginxport="$(netstat -nlpt | grep -i nginx | grep -i -m1 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"

echo ""
echo "IPv6 : [$ipv6_status]"
echo "Timezone : [$timezone]"
echo "UFW : [$ufwstatus]"
echo "Reboot : [12 AM]"
echo ""
echo "Port OpenSSH : [$opensshport]"
echo "Port Dropbear : [$dropbearport]"
echo "Port Stunnel : [$stunnel4port]"
echo "Port Squid : [$squidport]"
echo "Port OpenVPN : [$openvpnport]"
echo "Port BadVPN-UDPGw : [$badvpnport]"
echo "Port Nginx : [$nginxport]"
echo "Port WireGuard : [$wireguardport]"
echo ""
echo "Webmin : http://$ipAddress:10000/"
echo ""
echo "OVPN Config:"
echo "http://$ipAddress/client-udp.ovpn"
echo "http://$ipAddress/client-tcp.ovpn"
echo ""
echo "Telegram: @iriszz"
echo ""
